# Generated by Django 6.0.2 on 2026-03-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_changed_at_user_role_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_user_role', 'Can change user roles')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_verified_by',
        ),
    ]
