# Generated by Django 6.0.2 on 2026-03-01 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTimeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_timeframe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.deliverytimeframe')),
                ('escrow_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.escrowperiod')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='invoice_items/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invoice.invoice')),
            ],
        ),
    ]
