# Generated by Django 6.0.2 on 2026-03-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_buyer_invoice_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='escrow_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='escrow_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
