"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
from urllib.parse import urlparse, parse_qsl
from dotenv import load_dotenv

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Environment variables
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'
SECRET_KEY = os.getenv('SECRET_KEY')

# Allowed hosts
if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
else:
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    "rest_framework.authtoken",
    'corsheaders',
    'apps.accounts.apps.AccountsConfig',
    'apps.buyerdashboard',
    'apps.escrow',
    'apps.invoice',
    'apps.payments',
    'apps.sellerdashboard',
]

AUTH_USER_MODEL = 'accounts.User'

# Middleware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    tmp = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmp.path[1:],
            'USER': tmp.username,
            'PASSWORD': tmp.password,
            'HOST': tmp.hostname,
            'PORT': tmp.port or 5432,
            'OPTIONS': dict(parse_qsl(tmp.query)),  # sslmode etc
        }
    }
else:
    # Local development fallback
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static / Media
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# CORS
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://127.0.0.1:5173",
        "http://localhost:5173",
    ]
else:
    CORS_ALLOWED_ORIGINS = os.getenv('PROD_CORS_ALLOWED_ORIGINS', '').split(',')

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Interswitch credentials
INTERSWITCH_CLIENT_ID = os.getenv('INTERSWITCH_CLIENT_ID')
INTERSWITCH_CLIENT_SECRET = os.getenv('INTERSWITCH_CLIENT_SECRET')
INTERSWITCH_ENV = os.getenv('INTERSWITCH_ENV')
INTERSWITCH_WEBHOOK_SECRET = os.getenv('INTERSWITCH_WEBHOOK_SECRET')
INTERSWITCH_WEBHOOK_IPS = ["172.26.40.95", "172.26.40.96"]
INTERSWITCH_MERCHANT_CODE = os.getenv('INTERSWITCH_MERCHANT_CODE')
INTERSWITCH_PAY_ITEM_ID = os.getenv('INTERSWITCH_PAY_ITEM_ID')
REDIRECT_URL = os.getenv('REDIRECT_URL')
INTERSWITCH_WEBPAY_URL = os.getenv('INTERSWITCH_WEBPAY_URL')

# Frontend
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://localhost:5173')